### ISSUE TITLE
No handlers could be found for logger "openravepy.ikfast"

### ISSUE THREAD

**Issue by lakshmip001** [roboticsleeds/ur5controller#6] opened 2019-03-13 07:47 UTC
I am new to openrave do I need to install singularity container. I ran the following steps
 roslaunch ur_modern_driver ur5_bringup.launch robot_ip:=192.168.1.231
and then 
rosrun ur5controller control_ur5.py 

I am using sympy 0.7.1

but I get following when I run control_ur5.py
```
rosrun ur5controller control_ur5.py 
2019-03-13 16:01:06,822 openrave [WARN] [urdf_loader.cpp:369 URDFLoader::ParseURDF] Link[arm_stand_link]: Only trimeshes are supported for visual geometry.
2019-03-13 16:01:06,823 openrave [WARN] [urdf_loader.cpp:369 URDFLoader::ParseURDF] Link[arm_to_force_torque_sensor_link]: Only trimeshes are supported for visual geometry.
2019-03-13 16:01:06,823 openrave [WARN] [catkin_finder.cpp:245 __cxx11::string or_urdf::CatkinFinder::find] Could not find file 'ur5controller' under catkin package 'ur5_description/ridgeback/base_computer_box.stl'!
2019-03-13 16:01:06,823 openrave [WARN] [urdf_loader.cpp:293 URDFLoader::ParseURDF] Link[base_computer_box_link]: Failed loading collision mesh 
2019-03-13 16:01:06,823 openrave [WARN] [catkin_finder.cpp:245 __cxx11::string or_urdf::CatkinFinder::find] Could not find file 'ur5controller' under catkin package 'ur5_description/ridgeback/base_computer_box.stl'!
2019-03-13 16:01:06,824 openrave [WARN] [urdf_loader.cpp:369 URDFLoader::ParseURDF] Link[force_sensor_cable_port_placeholder_link]: Only trimeshes are supported for visual geometry.
2019-03-13 16:01:06,889 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/ridgeback_base_link with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,889 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/base with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,895 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/imu_link with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,895 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/mid_mount with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,895 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/robotiq_force_torque_frame_id with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,897 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/robotiq_fts_toolside with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,899 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/tool0 with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,909 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/ridgeback_base_link with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,909 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/base with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,915 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/imu_link with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,915 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/mid_mount with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,915 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/robotiq_force_torque_frame_id with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,917 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/robotiq_fts_toolside with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:06,919 openrave [WARN] [fclspace.h:248 FCLSpace::KinBodyInfoPtr fclrave::FCLSpace::InitKinBody] Initializing link ur5/tool0 with 0 geometries (env 1) (userdatakey fclcollision0x3ee5930)
2019-03-13 16:01:07,094 openrave [INFO] [?:-1 ?] The IKModel for UR5 robot is now being generated. Please be patient, this will take a while (sometimes up to 30 minutes)...
No handlers could be found for logger "openravepy.ikfast"
Traceback (most recent call last):
  File "/home/lakshmi/catkin_ws/src/ur5controller/scripts/control_ur5.py", line 155, in <module>
    demo = Demo()
  File "/home/lakshmi/catkin_ws/src/ur5controller/scripts/control_ur5.py", line 45, in __init__
    is_simulation=False)
  File "/home/lakshmi/catkin_ws/src/ur5controller/pythonsrc/ur5_robot/ur5_factory.py", line 136, in create_ur5_and_env
    self.robot.__init__(is_simulation)
  File "/home/lakshmi/catkin_ws/src/ur5controller/pythonsrc/ur5_robot/ur5_robot.py", line 62, in __init__
    self.ikmodel.autogenerate()
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/databases/inversekinematics.py", line 658, in autogenerate
    self.generate(iktype=iktype,freejoints=freejoints,precision=precision,forceikbuild=forceikbuild,outputlang=outputlang,ipython=ipython,ikfastmaxcasedepth=ikfastmaxcasedepth)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/databases/inversekinematics.py", line 889, in generate
    chaintree = solver.generateIkSolver(baselink=baselink,eelink=eelink,freeindices=self.freeindices,solvefn=solvefn)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 2295, in generateIkSolver
    chaintree = solvefn(self, LinksRaw, jointvars, isolvejointvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/databases/inversekinematics.py", line 751, in solveFullIK_6D
    return self.ikfast.IKFastSolver.solveFullIK_6D(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 2950, in solveFullIK_6D
    tree = self.solveFullIK_6DGeneral(T0links, T1links, solvejointvars, endbranchtree, usesolvers=1)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 3285, in solveFullIK_6DGeneral
    leftovertree = self.SolveAllEquations(AllEquationsExtra,curvars=curvars,othersolvedvars = self.freejointvars+usedvars,solsubs = solsubs,endbranchtree=origendbranchtree)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 6872, in SolveAllEquations
    return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 7238, in AddSolution
    nextsolutions[var] = self.SolveAllEquations(AllEquations,curvars=newvars,othersolvedvars=othersolvedvars+[var],solsubs=solsubs+self.Variable(var).subs,endbranchtree=endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 6732, in SolveAllEquations
    return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 7238, in AddSolution
    nextsolutions[var] = self.SolveAllEquations(AllEquations,curvars=newvars,othersolvedvars=othersolvedvars+[var],solsubs=solsubs+self.Variable(var).subs,endbranchtree=endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 6732, in SolveAllEquations
    return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 7536, in AddSolution
    newtree = self.SolveAllEquations(NewEquationsClean,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=newcases, currentcasesubs=newcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 6732, in SolveAllEquations
    return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 7536, in AddSolution
    newtree = self.SolveAllEquations(NewEquationsClean,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=newcases, currentcasesubs=newcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 6732, in SolveAllEquations
    return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 7094, in AddSolution
    ss += self.solveSingleVariable([checksimplezeroexpr.subs([(sothervar,sin(othervar)),(cothervar,cos(othervar))])],othervar,othersolvedvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 8553, in solveSingleVariable
    return [self.solveHighDegreeEquationsHalfAngle(eqns,varsym)]
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 8124, in solveHighDegreeEquationsHalfAngle
    pfinal = self.checkFinalEquation(pfinal,subs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 8181, in checkFinalEquation
    roots = mpmath.polyroots(numpy.array(numpy.array(coeffs),numpy.float64))
  File "/usr/lib/python2.7/dist-packages/mpmath/calculus/polynomials.py", line 189, in polyroots
    % maxsteps)
mpmath.libmp.libhyper.NoConvergence: Didn't converge in maxsteps=50 steps.

```
Help me how I can solve this problem.

**Comment by rpapallas** [comment] 2019-03-15 10:11
Closed duplicate of #7

**Closed as completed by rpapallas** 2019-03-15 10:11 UTC
Labels: duplicate
